# Site settings
title: Vivekanand Rao's Portfolio
email: vivekanand.rao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio theme built using Jekyll static site generator. In addition, to Jekyll also
  makes use of Markdown for writing our blog posts, Liquid for building out the page
  templates and Sass for styling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: viveksrao
github_username:  viveksrao

permalink: /:categories/:title

links:
  - title: about
    url:  /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
